# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20180119_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='filter_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(max_length=100),
        ),
    ]
