# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20180119_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='filter_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Subcategory'),
        ),
    ]
