# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-11 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='hola'),
            preserve_default=False,
        ),
    ]
