# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-06 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190706_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesproduct',
            name='image_120',
            field=models.ImageField(blank=True, upload_to='images/120'),
        ),
        migrations.AlterField(
            model_name='imagesproduct',
            name='image_200',
            field=models.ImageField(blank=True, upload_to='images/200'),
        ),
        migrations.AlterField(
            model_name='imagesproduct',
            name='image_600',
            field=models.ImageField(blank=True, upload_to='images/600'),
        ),
    ]
