# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-06 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190706_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesproduct',
            name='image_120',
        ),
        migrations.RemoveField(
            model_name='imagesproduct',
            name='image_200',
        ),
        migrations.RemoveField(
            model_name='imagesproduct',
            name='image_600',
        ),
        migrations.AddField(
            model_name='imagesproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='imagesproduct',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/thumbnail/'),
        ),
    ]
