# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-08 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190706_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesproduct',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/thumbnail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
