# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-21 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190801_1621'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='delete',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
        migrations.AlterField(
            model_name='imagesproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
