# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180119_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='filter',
        ),
    ]
