# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20180119_1919'),
        ('products', '0004_remove_product_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Filter'),
        ),
    ]
