# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180119_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_name',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
