# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinfo_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='last_name',
        ),
    ]
