# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userinfo_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userinfo',
            new_name='UserProfile',
        ),
    ]
